name: "pull request workflow"

on:
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pr-labeler:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: pr labeler
        uses: actions/labeler@v5
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          configuration-path: .github/labeler.yml

  rust-build-and-tests:
    runs-on: ubuntu-latest
    container: ghcr.io/benbenbang/uv-shell/prek
    permissions:
      contents: read
      pull-requests: write
      packages: read
    steps:
      - name: checkout repository
        uses: actions/checkout@v5
      - name: build binary
        run: cargo build --verbose
      - name: run test
        run: cargo test --verbose
    env:
      CARGO_TERM_COLOR: always
